/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.77
 * Generated at: 2017-06-13 16:25:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Time_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t$(document).ready(function(){\n");
      out.write("\t\tsubmitTweet();\n");
      out.write("\t});\n");
      out.write("</script>\n");
      out.write("<div class=\"bodyLeft\">\n");
      out.write("\t<div class=\"profileSide\">\n");
      out.write("\t\t<div class =\"profileInfo\">\n");
      out.write("\t\t\t<div class=\"head\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"info\">\n");
      out.write("\t\t\t\t<img src=\"imgs/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" alt=\"icon\">\n");
      out.write("\t\t\t\t<div class=\"name\">\n");
      out.write("\t\t\t\t<p class=\"clickable\" onclick=\"goProfile('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("')\"><b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</b></p>\n");
      out.write("\t\t\t\t<p class=\"clickable smallLink\" onclick=\"goProfile('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("')\">@");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"stats\">\n");
      out.write("\t\t\t<div><p>TWEETS</p><p class=\"num\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.tweets}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</p></div>\n");
      out.write("\t\t\t<div><p>FOLLOWING</p><p class=\"num\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.following}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</p></div>\n");
      out.write("\t\t\t<div><p>FOLLOWERS</p><p class=\"num\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.followers}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</p></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"TTSide\">\n");
      out.write("\t\t<div class =\"TTcontent\">\n");
      out.write("\t\t\t<p class=\"title\">Trending Topics</p>\n");
      out.write("\t\t\t<p class=\"hashtag clickable\">#Barcelona</p>\n");
      out.write("\t\t\t<p class=\"hashtag clickable\">#Lund</p>\n");
      out.write("\t\t\t<p class=\"hashtag clickable\">#CacatuasPower</p>\n");
      out.write("\t\t\t<p class=\"hashtag clickable\">#Reticulos</p>\n");
      out.write("\t\t\t<p class=\"hashtag clickable\">#DoItForYourLover</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<div class=\"bodyCenter\">\n");
      out.write("\t<p class=\"type\" style=\"display: none\"> Timeline </p>\n");
      out.write("\t<div class=\"input\">\n");
      out.write("\t\t<img src=\"imgs/logo_user.png\" alt=\"img\">\n");
      out.write("\t\t<form class=\"tweetInput\">\n");
      out.write("\t\t\t<textarea id=\"inputTweet\" maxlength=\"140\" name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" placeholder=\"What a hack?\"></textarea>\n");
      out.write("\t\t</form>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"tweets\">\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Tweets.jsp", out, false);
      out.write("\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<div class=\"bodyRight\">\n");
      out.write("\t<div class=\"usersSide\">\n");
      out.write("\t\t<div class =\"usersInfo\">\n");
      out.write("\t\t\t<p class=\"title\">MVP Users</p>\n");
      out.write("\t\t\t<div class=\"userBlock clickable\">\t\t\n");
      out.write("\t\t\t\t\t<img alt=\"user image\" src=\"imgs/logo_user.png\">\n");
      out.write("\t\t\t\t\t<div class=\"info\">\n");
      out.write("\t\t\t\t\t\t<p class=\"user\">@mgm793</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\t\n");
      out.write("\t\t\t<div class=\"userBlock clickable\">\t\t\n");
      out.write("\t\t\t\t\t<img alt=\"user image\" src=\"imgs/logo_user.png\">\n");
      out.write("\t\t\t\t\t<div class=\"info\">\n");
      out.write("\t\t\t\t\t\t<p class=\"user\">@mgm793</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\t\n");
      out.write("\t\t\t<div class=\"userBlock clickable\">\t\t\n");
      out.write("\t\t\t\t\t<img alt=\"user image\" src=\"imgs/logo_user.png\">\n");
      out.write("\t\t\t\t\t<div class=\"info\">\n");
      out.write("\t\t\t\t\t\t<p class=\"user\">@mgm793</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\t\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
